#!/usr/bin/env python3
"""Replay pure trajectory control from recorded teleop snapshots."""

from __future__ import annotations

import argparse
import importlib
import json
import re
import sys
import time
from pathlib import Path
from typing import Any

import numpy as np
import torch
from isaaclab.app import AppLauncher

_FULL_TRA_DIR = Path(__file__).resolve().parent
if str(_FULL_TRA_DIR) not in sys.path:
    sys.path.insert(0, str(_FULL_TRA_DIR))
from full_tra_task_entries import resolve_env_cfg_entries


def _repo_root() -> Path:
    p = Path(__file__).resolve().parent
    for _ in range(10):
        if (p / "source").is_dir():
            return p
        if p.parent == p:
            break
        p = p.parent
    return Path(__file__).resolve().parents[3]


def _load_symbol(entry: str) -> Any:
    mod_name, sym_name = entry.split(":", 1)
    mod = importlib.import_module(mod_name)
    return getattr(mod, sym_name)


def _to_numpy(x) -> np.ndarray:
    if torch.is_tensor(x):
        return x.detach().cpu().numpy()
    return np.asarray(x, dtype=np.float64)


def _build_arg_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="Play pure full_tra trajectory from teleop recorder JSON.")
    p.add_argument(
        "--task",
        type=str,
        default=None,
        help="Override preset / Gym id for env loading. Default: use trajectory JSON env_entry/cfg_entry, else doc['task'].",
    )
    p.add_argument("--env", type=str, default="")
    p.add_argument("--cfg", type=str, default="")
    p.add_argument("--num_envs", type=int, default=1)
    p.add_argument("--fps", type=float, default=30.0)
    p.add_argument("--max-steps", type=int, default=0, help="0 = until app closed.")
    p.add_argument("--trajectory-file", type=str, required=True, help="JSON generated by GUI recorder.")
    p.add_argument("--arm-base-pos", type=float, nargs=3, default=(0.0, 0.0, 0.0))
    p.add_argument("--arm-base-euler", type=float, nargs=3, default=(0.0, 0.0, 0.0))
    p.add_argument("--manual-reset-every", type=int, default=0, help="If >0, call env.reset every N steps.")
    p.add_argument("--arm-pos-tol", type=float, default=0.05, help="Arm joint convergence tolerance (rad).")
    p.add_argument("--hand-pos-tol", type=float, default=0.08, help="Hand joint convergence tolerance (rad).")
    p.add_argument("--stable-steps", type=int, default=5, help="Need N consecutive converged steps to switch frame.")
    p.add_argument("--max-steps-per-frame", type=int, default=240, help="Force switch if a frame cannot converge.")
    p.add_argument(
        "--post-arm-reached-steps",
        type=int,
        default=30,
        help="After arm reaches target, wait at most N more steps before switching frame.",
    )
    AppLauncher.add_app_launcher_args(p)
    return p


def main() -> int:
    args = _build_arg_parser().parse_args()
    app_launcher = AppLauncher(args)
    simulation_app = app_launcher.app

    import ViTacLab.tasks  # noqa: F401

    repo_root = _repo_root()
    source_dir = repo_root / "source"
    if str(source_dir) not in sys.path:
        sys.path.insert(0, str(source_dir))

    from video_teleop.core.shadowhand_joints import shadowhand_joint_names
    from video_teleop.core.video_teleop_control import VideoTeleopControl

    traj_path = Path(str(args.trajectory_file)).expanduser()
    if not traj_path.is_absolute():
        traj_path = (repo_root / traj_path).resolve()
    doc = json.loads(traj_path.read_text(encoding="utf-8"))
    frames = list(doc.get("frames") or [])
    if not frames:
        raise RuntimeError(f"trajectory has no frames: {traj_path}")
    print(f"[INFO] Loaded trajectory {traj_path} with {len(frames)} frames.")

    env_s = str(args.env).strip()
    cfg_s = str(args.cfg).strip()
    doc_env = doc.get("env_entry")
    doc_cfg = doc.get("cfg_entry")
    traj_task = doc.get("task")

    if env_s and cfg_s:
        env_entry, cfg_entry = env_s, cfg_s
        print(f"[INFO] env/cfg from CLI: {env_entry} / {cfg_entry}")
    elif args.task is not None:
        env_entry, cfg_entry, _pk = resolve_env_cfg_entries(task=str(args.task).strip(), env="", cfg="")
        print(f"[INFO] env/cfg from --task: {env_entry} / {cfg_entry}")
    elif (
        isinstance(doc_env, str)
        and isinstance(doc_cfg, str)
        and doc_env.strip()
        and doc_cfg.strip()
    ):
        env_entry, cfg_entry = doc_env.strip(), doc_cfg.strip()
        print(f"[INFO] env/cfg from trajectory JSON: {env_entry} / {cfg_entry}")
    else:
        task_for = str(traj_task or "pickup").strip()
        env_entry, cfg_entry, _pk = resolve_env_cfg_entries(task=task_for, env="", cfg="")
        print(f"[INFO] env/cfg resolved from trajectory task={task_for!r}: {env_entry} / {cfg_entry}")

    EnvCls = _load_symbol(env_entry)
    CfgCls = _load_symbol(cfg_entry)

    cfg = CfgCls()
    cfg.scene.num_envs = max(1, int(args.num_envs))
    cfg.device = getattr(args, "device", None) or "cuda:0"
    env = EnvCls(cfg)
    robot = env.robot
    joint_names = list(robot.joint_names)
    arm_expr = getattr(cfg, "arm_joint_expr", ".*(shoulder|elbow|wrist_1|wrist_2|wrist_3|ur10).*")
    hand_expr = getattr(cfg, "hand_joint_expr", ".*(FFJ|MFJ|RFJ|LFJ|THJ|WRJ).*")
    arm_indices = [i for i, n in enumerate(joint_names) if re.match(arm_expr, n)]
    hand_indices = [i for i, n in enumerate(joint_names) if re.match(hand_expr, n)]
    sh_names = shadowhand_joint_names()
    env.reset()
    action_dim = env.num_actions

    def _sample_object_pos_env() -> np.ndarray:
        if hasattr(env, "object") and hasattr(env.object, "data"):
            return _to_numpy(env.object.data.root_pos_w[0] - env.scene.env_origins[0]).ravel()[:3]
        if hasattr(env, "cup") and hasattr(env.cup, "data"):
            return _to_numpy(env.cup.data.root_pos_w[0] - env.scene.env_origins[0]).ravel()[:3]
        return np.zeros(3, dtype=np.float64)

    def _object_init_pos_env() -> np.ndarray:
        if hasattr(cfg, "object_cfg"):
            pos = getattr(getattr(cfg, "object_cfg"), "init_state", None)
            if pos is not None and hasattr(pos, "pos"):
                return np.asarray(pos.pos, dtype=np.float64).ravel()[:3]
        if hasattr(cfg, "cup_cfg"):
            pos = getattr(getattr(cfg, "cup_cfg"), "init_state", None)
            if pos is not None and hasattr(pos, "pos"):
                return np.asarray(pos.pos, dtype=np.float64).ravel()[:3]
        return np.zeros(3, dtype=np.float64)

    def _hand_joint_for_robot_name(name: str, hand_joints: np.ndarray) -> float:
        for sh_idx, sh_name in enumerate(sh_names):
            if sh_name in name or name.endswith(sh_name):
                return float(hand_joints[sh_idx])
        return 0.0

    def _current_arm_joints() -> np.ndarray:
        jpos = robot.data.joint_pos[0].detach().cpu().numpy()
        return np.array([float(jpos[idx]) for idx in arm_indices], dtype=np.float64)

    def _current_hand_shadow24() -> np.ndarray:
        out = np.zeros(24, dtype=np.float64)
        jpos = robot.data.joint_pos[0].detach().cpu().numpy()
        for sh_i, sh_name in enumerate(sh_names):
            for idx in hand_indices:
                n = joint_names[idx]
                if sh_name in n or n.endswith(sh_name):
                    out[sh_i] = float(jpos[idx])
                    break
        return out

    def _build_action(arm_joints: np.ndarray, hand_joints: np.ndarray) -> torch.Tensor:
        full_dof = np.zeros(robot.num_joints, dtype=np.float64)
        for i, idx in enumerate(arm_indices):
            if i < len(arm_joints):
                full_dof[idx] = float(arm_joints[i])
        for idx in hand_indices:
            full_dof[idx] = _hand_joint_for_robot_name(joint_names[idx], hand_joints)
        actuated = full_dof[np.array(env.actuated_dof_indices, dtype=np.int64)]
        lower = env.robot_dof_lower_limits[0, env.actuated_dof_indices].cpu().numpy()
        upper = env.robot_dof_upper_limits[0, env.actuated_dof_indices].cpu().numpy()
        eps = 1e-6
        scale = np.where(upper - lower > eps, 2.0 * (actuated - lower) / (upper - lower) - 1.0, 0.0)
        scale = np.clip(scale, -1.0, 1.0)
        return torch.tensor(scale, dtype=torch.float32, device=env.device).unsqueeze(0)

    from scipy.spatial.transform import Rotation as R

    def _make_T(pos_xyz: np.ndarray, euler_xyz: np.ndarray) -> np.ndarray:
        T = np.eye(4, dtype=np.float64)
        T[:3, :3] = R.from_euler("xyz", np.asarray(euler_xyz, dtype=np.float64), degrees=False).as_matrix()
        T[:3, 3] = np.asarray(pos_xyz, dtype=np.float64)
        return T

    T_world_arm_base = _make_T(np.array(args.arm_base_pos, dtype=np.float64), np.array(args.arm_base_euler, dtype=np.float64))
    control = VideoTeleopControl(T_world_arm_base=T_world_arm_base)

    target_dt = 1.0 / max(1e-3, float(args.fps))
    step = 0
    frame_idx = 0
    stable_count = 0
    arm_reached_countdown = -1
    step_in_frame = 0
    while simulation_app.is_running():
        t0 = time.time()
        step += 1
        fr = frames[frame_idx % len(frames)]
        marker_pos = np.asarray(fr.get("marker_pos_w", [0.65, 0.12, 0.42]), dtype=np.float64).ravel()[:3]
        marker_euler = np.asarray(fr.get("marker_euler_xyz", [0.0, 2.2, 0.0]), dtype=np.float64).ravel()[:3]
        obj_rand = np.asarray(fr.get("object_pos_env_random", [0.0, 0.0, 0.0]), dtype=np.float64).ravel()[:3]
        hand_j = np.asarray(fr.get("hand_joint_pos_shadow_order", [0.0] * 24), dtype=np.float64).ravel()
        obj_cur_rand = _sample_object_pos_env() - _object_init_pos_env()
        # Random compensation only uses x/y; ignore z offset.
        obj_rand[2] = 0.0
        obj_cur_rand[2] = 0.0
        wrist_pos = marker_pos - obj_rand + obj_cur_rand
        targets = control.compute(wrist_pos, marker_euler, hand_j)
        if targets is None:
            actions = torch.zeros(env.num_envs, action_dim, device=env.device)
            converged_now = False
            arm_reached_now = False
        else:
            actions = _build_action(targets.arm_joints, targets.hand_joints)
            cur_arm = _current_arm_joints()
            cur_hand = _current_hand_shadow24()
            arm_err = float(np.max(np.abs(cur_arm - np.asarray(targets.arm_joints, dtype=np.float64))))
            hand_err = float(np.max(np.abs(cur_hand - np.asarray(targets.hand_joints, dtype=np.float64))))
            arm_reached_now = arm_err <= float(args.arm_pos_tol)
            converged_now = (arm_err <= float(args.arm_pos_tol)) and (hand_err <= float(args.hand_pos_tol))
        if env.num_envs > 1:
            actions = actions.expand(env.num_envs, -1).clone()
        env.step(actions)
        step_in_frame += 1
        if converged_now:
            stable_count += 1
        else:
            stable_count = 0
        if arm_reached_countdown < 0 and arm_reached_now:
            arm_reached_countdown = max(0, int(args.post_arm_reached_steps))
        elif arm_reached_countdown >= 0:
            arm_reached_countdown -= 1
        should_advance = (
            stable_count >= max(1, int(args.stable_steps))
            or step_in_frame >= max(1, int(args.max_steps_per_frame))
            or (arm_reached_countdown == 0)
        )
        if should_advance:
            frame_idx = (frame_idx + 1) % len(frames)
            stable_count = 0
            arm_reached_countdown = -1
            step_in_frame = 0
        if int(args.manual_reset_every) > 0 and step % int(args.manual_reset_every) == 0:
            env.reset()
        if args.max_steps > 0 and step >= int(args.max_steps):
            break
        elapsed = time.time() - t0
        if target_dt - elapsed > 0:
            time.sleep(target_dt - elapsed)

    env.close()
    simulation_app.close()
    return 0

    
if __name__ == "__main__":
    raise SystemExit(main())
